[package]
name = "nanogpt"
version = "0.1.0"
edition = "2024"

[profile.release]
lto = true
# codegen-units = 1

[dependencies]
anyhow = "1.0.98"
burn = { version = "0.17.0", features = ["train", "wgpu"] }
rand = "0.9.1"
serde = "1.0.219"
serde_json = "1.0.140"
