[package]
name = "nanogpt"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
burn = { version = "0.16.1", features = ["wgpu"] }
rand = "0.9.1"
reqwest = "0.12.15"
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread"] }
